# Generated by Django 3.2.4 on 2021-06-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Canceled')], default='Pending', max_length=15)),
                ('check_in', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('check_out', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('payment_number', models.CharField(max_length=20)),
                ('trnxid', models.CharField(max_length=250)),
                ('booking_id', models.CharField(default='null', max_length=100)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
