# Generated by Django 3.2.4 on 2021-06-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210619_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('payment_number', models.CharField(max_length=20, null=True)),
                ('trxid', models.CharField(max_length=250, null=True)),
                ('paymentStatus', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Due'), ('4', 'Canceled')], default='Pending', max_length=15)),
                ('nid', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=250, null=True)),
                ('marital_status', models.CharField(max_length=250, null=True)),
                ('father_name', models.CharField(max_length=250, null=True)),
                ('mother_name', models.CharField(max_length=250, null=True)),
                ('policeStatus', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Canceled')], default='Pending', max_length=15)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
