# Generated by Django 3.2.4 on 2021-06-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210620_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='trnxid',
        ),
    ]
